### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zhangxin9988** [RUCKBReasoning/P-INT#2]
作者你好，非常感谢你的工作。
在复现代码时遇到了一个bug，您知道这是什么原因吗？
(pytorch) zx@pc-PowerEdge-T640:~/codes/P-INT$ python train.py --dataset "NELL-One" --few 5 --max_batches 200000
------HYPERPARAMETERS-------
dataset: NELL-One
embed_dim: 100
hidden_dim: 100
mode: test
few: 5
batch_size: 32
random_embed: False
lr: 0.0005
margin: 64.0
max_batches: 200000
dropout: 0.2
log_every: 100
test: False
grad_clip: 5.0
weight_decay: 0.0
embed_model: TransE
prefix: intial
seed: 88
epoch: 3
hop: 3
max_neighbor: 200
eval_every: 100
neighbor_limit: 300
topk: 100
kernel_num: 21
save_path: models/NELL-One5intial
----------------------------
2022-08-24 18:47:30 INFO: - START TRAINING...
5/200000Traceback (most recent call last):
  File "/data/zx/codes/P-INT/train.py", line 48, in <module>
    main(args)
  File "/data/zx/codes/P-INT/train.py", line 15, in main
    trainer.train() # train
  File "/data/zx/codes/P-INT/trainer.py", line 274, in train
    loss = self.T_GRUA(support_pair, support_rel, support_path, query_head, query_tail, one_tomany_train, self.cos_rel_all, True, candidates_id)
  File "/data/zx/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/zx/codes/P-INT/net.py", line 153, in forward
    tree_q, tree_all_emb, parent_index, parent_node, aim_rel_all = self.T_GRUQ(support_tree_emb, support_rel, query_head, cos_rel_all, t_h, True)
  File "/data/zx/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/zx/codes/P-INT/net.py", line 380, in forward
    m = torch.distributions.multinomial.Multinomial(total_count=self.topk, logits=score_max)
  File "/data/zx/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributions/multinomial.py", line 64, in __init__
    super(Multinomial, self).__init__(batch_shape, event_shape, validate_args=validate_args)
  File "/data/zx/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/distributions/distribution.py", line 53, in __init__
    raise ValueError("The parameter {} has invalid values".format(param))
ValueError: The parameter probs has invalid values

**Comment by zhangweijian97** [comment]
我也遇到这个问题

```
python train.py
------HYPERPARAMETERS-------
dataset: NELL-One
embed_dim: 100
hidden_dim: 100
mode: test
few: 1
batch_size: 32
random_embed: False
lr: 0.0005
margin: 64.0
max_batches: 200000
dropout: 0.2
log_every: 100
test: False
grad_clip: 5.0
weight_decay: 0.0
embed_model: TransE
prefix: intial
seed: 88
epoch: 3
hop: 3
max_neighbor: 200
eval_every: 100
neighbor_limit: 300
topk: 100
kernel_num: 21
save_path: models/NELL-One1intial
----------------------------
2022-11-15 16:05:56 INFO: - START TRAINING...
1/200000
3/200000
5/200000
6/200000
Traceback (most recent call last):
  File "train.py", line 48, in <module>
    main(args)
  File "train.py", line 15, in main
    trainer.train() # train
  File "/Users/zhangweijian/CodeRepo/PhDyear2/P-INT/trainer.py", line 275, in train
    loss = self.T_GRUA(support_pair, support_rel, support_path, query_head, query_tail, one_tomany_train, self.cos_rel_all, True, candidates_id)
  File "/Users/zhangweijian/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/zhangweijian/CodeRepo/PhDyear2/P-INT/net.py", line 153, in forward
    tree_q, tree_all_emb, parent_index, parent_node, aim_rel_all = self.T_GRUQ(support_tree_emb, support_rel, query_head, cos_rel_all, t_h, True)
  File "/Users/zhangweijian/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/zhangweijian/CodeRepo/PhDyear2/P-INT/net.py", line 391, in forward
    m = torch.distributions.multinomial.Multinomial(total_count=self.topk, logits=score_max)
  File "/Users/zhangweijian/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/distributions/multinomial.py", line 68, in __init__
    super(Multinomial, self).__init__(batch_shape, event_shape, validate_args=validate_args)
  File "/Users/zhangweijian/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/distributions/distribution.py", line 57, in __init__
    f"Expected parameter {param} "
ValueError: Expected parameter probs (Tensor of shape (32, 30000)) of distribution Multinomial() to satisfy the constraint Simplex(), but found invalid values:
tensor([[4.7630e-05, 5.2274e-05, 5.5445e-05,  ..., 3.2594e-05, 3.2594e-05,
         3.2594e-05],
        [5.3388e-05, 5.3730e-05, 5.6998e-05,  ..., 3.3327e-05, 3.3327e-05,
         3.3327e-05],
        [5.6419e-05, 5.3044e-05, 5.3203e-05,  ..., 3.3212e-05, 3.3212e-05,
         3.3212e-05],
        ...,
        [5.9308e-05, 5.3940e-05, 5.3905e-05,  ..., 3.3173e-05, 3.3173e-05,
         3.3173e-05],
        [5.5466e-05, 5.2581e-05, 5.2749e-05,  ..., 3.3165e-05, 3.3165e-05,
         3.3165e-05],
        [3.3333e-05, 3.3333e-05, 3.3333e-05,  ..., 3.3333e-05, 3.3333e-05,
         3.3333e-05]])
```

**Comment by zhangweijian97** [comment]
这里我没找到解决办法，只能catch error然后用小于0.8那边的代码替代

**Comment by CurryaNa** [comment]
> 这里我没找到解决办法，只能catch error然后用小于0.8那边的代码替代

你好，想问下你是怎么catch error然后用小于0.8那边的代码替代的，能详细说下吗，我也遇到这个报错，不知道咋解决的

**Comment by lssshuang** [comment]
> > 这里我没找到解决办法，只能catch error然后用小于0.8那边的代码替代
> 
> 你好，想问下你是怎么catch error然后用小于0.8那边的代码替代的，能详细说下吗，我也遇到这个报错，不知道咋解决的

你好，我也遇到这个问题，请问你现在解决了吗
